#!/usr/bin/env python3 


def login(email, password):
    time.sleep(4)
    email_input = driver.find_element(By.NAME , "email")
    email_input.send_keys(email)

    submit_button = driver.find_element(By.XPATH , '//*[@id="signin-submit"]/button')
    submit_button.click()

    time.sleep(15)

    try:
        close_button = driver.find_element(By.XPATH , "//button[@aria-label='Close']")
        close_button.click()
    except:
        pass

    # wait for password field to appear
    password_input = WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'input[type="password"]'))
    )
    password_input.send_keys(password + Keys.ENTER)

    time.sleep(15)



