#!/usr/bin/env python3 
from selenium import webdriver
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
import time
import random


driver = webdriver.Chrome()
driver.get("https://badoo.com")

driver.implicitly_wait(20)

email = "0638278510"
password = "Aissaoui@2007"

def login(email, password):
    time.sleep(4)
    driver.find_element(By.NAME , "email").send_keys(email + Keys.ENTER)
    driver.find_element(By.NAME , "password").send_keys(password + Keys.ENTER)

    submit_button = driver.find_element(By.XPATH , '//*[@id="signin-submit"]/button')

#    email_input.send_keys(email)
#    password_input.send_keys(password)
    submit_button.click()

    time.sleep(15)

    try:
        close_button = driver.find_element(By.XPATH , "//button[@aria-label='Close']")
        close_button.click()
    except:
        pass

login(email , password)
time.sleep(200)
