#!/usr/bin/env python3 

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options as opt
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.alert import Alert
from selenium.common.exceptions import NoAlertPresentException
import time
import re , random 


juba = opt()
juba.add_experimental_option("detach", True)
driver = webdriver.Chrome(options=juba)
time.sleep(3)

driver.get("https://badoo.com")
driver.implicitly_wait(10)


email = "0668646370"
password = "Aissaoui@2007"

# like and dislike Xpaths 
like = '//*[@id="mm_cc"]/div[1]/section/div/div[2]/div/div[2]/div[1]/button'
dislike = '//*[@id="mm_cc"]/div[1]/section/div/div[2]/div/div[2]/div[2]/button'

def login():

    try:
        time.sleep(3)
        sign_in = driver.find_element(By.XPATH,'//*[@id="header"]/div/div[2]/div/div/a' )
        sign_in.click() 
    except:
        print("sign in failed")

    try:
        time.sleep(3)
        email_input = driver.find_element(By.XPATH,'//*[@id="signin-name"]')
        email_input.send_keys(email)
    except:
        print("no email")

    try:
        time.sleep(2)
        password_input = driver.find_element(By.XPATH , '//*[@id="signin-password"]') 
        password_input.send_keys(password + Keys.ENTER)
    except:
        print(" no password")

    try:
        time.sleep(2)
        submit_button = driver.find_element(By.XPATH , '//*[@id="signin-submit"]/button')
        submit_button.click()
    except:
        print("no submit button ")
    time.sleep(30)

login()


def dismiss_alert():
    """Dismiss any alert dialogs present on the page"""
    try:
        alert = driver.switch_to.alert
        alert.dismiss()
    except NoAlertPresentException:
        pass
    except UnexpectedAlertPresentException:
        alert = driver.switch_to.alert
        alert.dismiss()
        dismiss_alert()



def like_dislike():

    for i in range(10):
        time.sleep(3)
        if i % 5 == 4:  # execute the second choice once every five iterations
            dislike_button = driver.find_element(By.XPATH , dislike)
            dislike_button.click()

        else:
            """ like 4 times """
            like_button = driver.find_element(By.XPATH , like)
            like_button.click()


def run_bot():
    dismiss_alert()
    like_dislike()

while True:
    run_bot()
